### ISSUE TITLE
Improve devex of Typescript SDK

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/sdk-typescript#204]
We need to take over the Typescript SDK.

```[tasklist]
### Tasks
- [ ] Transfer context from previous owners
- [ ] #15
- [ ] #21
- [ ] https://github.com/restatedev/sdk-typescript/issues/101
- [ ] https://github.com/restatedev/sdk-typescript/issues/197
- [ ] https://github.com/restatedev/node-template-generator/issues/18
- [ ] https://github.com/restatedev/restate/issues/898
- [ ] https://github.com/restatedev/sdk-typescript/issues/187
- [ ] https://github.com/restatedev/restate/issues/899
- [ ] https://github.com/restatedev/sdk-typescript/issues/199
```

**Comment by slinkydeveloper** [comment]
Closing this issue as we're already tracking the singular issues separately and this adds noise.
