### ISSUE TITLE
Await with duration to do timeout in Promise.any/all

### ISSUE THREAD

**Issue by gvdongen** [restatedev/sdk-typescript#21]
```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/sdk-typescript/issues/15
- [ ] https://github.com/restatedev/sdk-typescript/issues/180
- [ ] https://github.com/restatedev/e2e/issues/216
```
