### ISSUE TITLE
Workflow API stabilization feedback

### ISSUE THREAD

**Issue by slinkydeveloper** [restatedev/sdk-typescript#260]
```[tasklist]
### Tasks
- [ ] When registering the deployment, I get overwhelmed by the methods and the different service. I know we cannot do otherwise b/c of how the implementation works, but it would be good to at least document this properly, maybe straight in the examples, to describe that this is "expected"
- [ ] The methods `getLatestMessage` and `pollNextMessages` are unused, i suggest to remove them for the time being
- [ ] Somehow we need to document what are the methods that are added to the workflow service, and how to invoke them from the outside, e.g. using `curl` or `httpie`. I found myself doing some trial and error to guess the parameters, also because in the implementation is not straightforward to understand the request input. For example: I was expecting `key` to be the workflow id, not `request[workflowId]`
- [ ] I think we should split read/side of the durable promise, both because it looks better and also because it makes clear the responsabilities (there should be one reader and one writer in theory). `ctx.promise()` being the read side, which directly returns the thenable the user can await on, and which also has peek method. `ctx.promiseHandle()` being the write side, has methods resolve and reject
- [ ] I can't resolve a promise with undefined, this seems like a bug because the interface is `resolve(T?)`. It also makes sense to allow that for "void" durable promises.
- [ ] Maybe the `start` method should be `submit` instead, as for the verb "submit workflow"?
- [ ] I can't use primitive types, such as simply `string`, for the workflow input. Looking at the implementation, this somewhat makes sense, although it's not aligned with the general behavior of the handler API where this is supported (and shown in our docs). We should at least make this prominent in the documentation.
- [ ] Some checks, such as setting state to undefined, are implemented on the state service, but not on the context interface. Because some of these operations are performed as background calls to the state service, the workflow service won't be notified of the fact that the set failed. We should perhaps perform those checks on the caller side as well.
```
